### ISSUE TITLE
[Need Solution]: Multiples of 3 and 5

### ISSUE THREAD

**Issue by hmharshit** [hmharshit/hacktoberfest#1]
Question Name - Multiples of 3 and 5

**Comment by Soheil-Rasouli** [comment]
Hi. Which language should we use for this project?

**Comment by xcyberpunkx0** [comment]
i am providing the code using c++

**Comment by hmharshit** [comment]
@mcrd25 

Thank you for your contribution. 
Multiple solutions for different programming languages are accepted.
I'll review your solution soon. Meanwhile, you may look into other issues also.

**Comment by chris-tse** [comment]
I would like to submit a solution in JavaScript if multiple solutions are accepted.

**Comment by odlarcos** [comment]
I am providing a solution in Python

**Comment by malik-aditya** [comment]
Hey, i would like to provide a solution in java.

**Comment by hmharshit** [comment]
Excellent work by these contributors for providing solutions in the following languages

1. @chris-tse --> JS
2. @xcyberpunkx0 --> C++
3. @mcrd25 --> Ruby

**Comment by giorg0s** [comment]
Hi there!
I'm providing a solution in C ;)

**Comment by hmharshit** [comment]
@giorg0s Whenever you are done, just re-open this issue and reference your PR.

**Comment by hmharshit** [comment]
I'm closing this issue. If anyone still wants to contribute a solution in different programming languages. They may re-open the issue and comment that they are working on this and specify the programming language they will be using.
