### ISSUE TITLE
[Need Solution]: Special Pythagorean triplet

### ISSUE THREAD

**Issue by hmharshit** [hmharshit/hacktoberfest#22]
Question Name - Special Pythagorean triplet

**Comment by DyspC** [comment]
Hi, I'm going to prepare this one using JS

**Comment by hmharshit** [comment]
Excellent work by these contributors for providing solutions in the following languages

@DyspC --> JavaScript

**Comment by hmharshit** [comment]
I'm closing this issue. If anyone still wants to contribute a solution in different programming languages. They may re-open the issue and comment that they are working on this and specify the programming language they will be using.
